name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Using GitHub actions bot user for deployments
      # https://api.github.com/users/github-actions[bot]
      GITHUB_ACTIONS_USER: github-actions[bot]
      GITHUB_ACTIONS_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          npm config set "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}"
          npm install
      - name: Build
        run: npm run build
      - name: deploy
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name $GITHUB_ACTIONS_USER
          git config user.email $GITHUB_ACTIONS_USER_EMAIL
          git remote set-url origin https://$GITHUB_ACTIONS_USER:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
          npm run export
          npm run deploy
